compilerla/pems

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/mkdocs.yml, .markdownlint.yaml, .pre-commit-config.yaml, .vscode/settings.json, compose.yml, docs/.pages, docs/README.md, docs/requirements.txt, mkdocs.yml
Closes #7 
This PR sets up the documentation similar to https://github.com/compilerla/template-devcontainer
- configures `mkdocs.yml`, based on https://github.com/compilerla/template-devcontainer/blob/main/mkdocs.yml
- creates a `docs/` directory
- creates `docs/requirements.txt` with dependencies
mdx_truly_sane_lists
mkdocs==1.6.1
mkdocs-awesome-pages-plugin
mkdocs-macros-plugin
mkdocs-material==9.5.44
mkdocs-redirects
- creates `docs/README.md` with basic information
- creates `docs` Compose service, starts with devcontainer, site is browsable locally
- creates GitHub Actions workflow that publishes docs to GitHub Pages
=> Feat: set up docs

.github/workflows/mkdocs.yml
Needs `write` permission to push the `gh-pages` branch. See failure here: https://github.com/compilerla/pems/actions/runs/12168357388/job/33938992891
I made the default permissions for GitHub Actions in this repo be `read`.
=> Fix: add write permissions for mkdocs

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/requirements.txt, pems/__init__.py, pyproject.toml
Closes #4
This PR prepares the outline for a Python project
- Set up pyproject.toml with project metadata, dependencies, and build system
- Set up __init__.py (and ready for dynamic package versioning)
- Install devcontainer requirements from pyproject.toml
- devcontainer is updated to use TOML VSCode extension
=> Feat: Python project outline

.dockerignore
Otherwise any existing directory is copied with the Docker build, which then fails on `pip install -e .[dev]`.
=> Fix: ignore .egg-info

.github/dependabot.yml, .github/workflows/codeql.yml, .github/workflows/dependency-triage.yml, .github/workflows/labeler-actions.yml, .github/workflows/labeler-docs.yml
Closes #8 
Closes #9 
Adds some workflows for adding PR labels, adding dependency PRs to the project, etc.
=> CI: add code quality workflows

.devcontainer/devcontainer.json, .env.sample, compose.yml
=> Refactor: make elastic service startup optional

.devcontainer/devcontainer.json, .dockerignore, .env.sample, .flake8, .vscode/launch.json, .vscode/settings.json, manage.py, pems/settings.py, pems/urls.py, pems/wsgi.py, pyproject.toml
Closes #5
This PR sets up a minimal runnable Django project. It includes:
- adding Django as a dependency
- initializing the PeMS Django project using a SQLite database
- setting up VS Code for Python projects (including setting up the debugger)
=> Feat: create runnable Django project

.devcontainer/devcontainer.json, .env.sample, bin/init.sh, bin/reset_db.sh, compose.yml, pems/settings.py
Closes #33
When the dev container starts, this PR:
- creates/resets the database
- runs migrations
- collects static files
- creates the Django superuser
=> Feat: initialize Django and create db

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/postAttach.sh, .dockerignore, .env.sample, .vscode/settings.json, appcontainer/Dockerfile, appcontainer/gunicorn.conf.py, appcontainer/nginx.conf, bin/start.sh, compose.yml, manage.py, pyproject.toml
Closes #10 
1. Checkout the branch locally (not in devcontainer)
2. Make sure there are no other pending changes
3. Add a sample git tag e.g. `git tag -a 2024.12.1`
4. Build the app container `docker compose build app`
5. Run the app container, confirm the version matches the sample tag `docker compose run --entrypoint /bin/bash app` then inside `python manage.py --version`
6. Rebuild and reload the devcontainer, confirm it still works
=> Feat: initial appcontainer setup

.github/workflows/mkdocs.yml
Closes #47 
I created the Netlify site `compiler-previews.netlify.app` and an auth token using the @compiler-bot account.
That auth token was added as an org secret in Compiler's GitHub, with only this repository given access to the secret.
The Netlify site ID was added as an org variable in Compiler's GitHub, with only this repository given access to the variable.
=> CI: publish docs preview site for PRs

.env.sample, .github/lighthouserc.json, .github/workflows/deploy.yml, .github/workflows/tests-ui.yml, compose.yml
Closes #11
This release workflow is triggered by pushing a calver formatted tag. The workflow:
- runs tests, builds the app container image, and pushes to GHCR
- for a release tag, it makes a GitHub release
=> CI: create release workflow

.github/workflows/deploy.yml
Removed the `if: github.ref_type == 'tag'` condition on `tests-ui` and `tests-pytest` in the `Deploy` workflow so that the tests run on all pushes (both commits and tags) to `main`.
=> CI: tests run for all pushes to main

docs/.pages, docs/development/README.md, mkdocs.yml
=> Docs: getting started guide

.github/workflows/deploy.yml
Removed the `if` condition on the `deploy` job so that deploy does not run regardless of the success or failure of `tests-ui` and `tests-pytest`, i.e., `needs` actually behaves as expected. Referred to the [warning note in the docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#always).
=> CI: deploy job runs only if tests pass

docs/README.md
Updated the main doc site page with product roadmap and some of the language Andy uses for Benefits (links to our sprint and milestones in the GitHub project). 
Had some trouble with the formatting on the Mermaid diagram (see Q4 of 2024 - for some reason the arrow disappeared and I can't get it back - maybe just too many boxes for the frame?). Not a huge deal, but if there's an easy fix I would welcome it!
Also - should this be its own page? Not sure yet how to build out separate markdown files as pages on a doc site, so I just updated the existing file.
=> Docs: add product roadmap

.github/ISSUE_TEMPLATE/release.yml, docs/.pages, docs/deployment/.pages, docs/deployment/hotfix.md, docs/deployment/release.md, docs/deployment/rollback.md
Closes #43
Closes #55
This documents how to make a tag-based release (regular, hotfix, and rollback) and creates the "Release process issue" template.
=> Docs: making a release

docs/README.md, docs/styles/theme.css, mkdocs.yml
- Disables dark mode
- Updates primary/accent color for contrast and accessibility
- Fixes colors on roadmap
=> Fix: Docs site theme and Roadmap style

tests/pytest/streamlit_app/test_utils.py
Closes #92
The discovered apps are now compared set-wise instead of ordered-wise. This is to ensure that the order of the apps does not matter and fixes a failing assertion that was seen locally but not in the CI.
=> Fix: `_discover_apps` test

pems/districts/templates/districts/district.html, pems/districts/templates/districts/index.html, pems/districts/urls.py, pems/districts/views.py, pems/urls.py, tests/pytest/conftest.py, tests/pytest/pems/districts/test_views.py
Closes #67 
This PR does the initial setup of the `urlpatterns`. It also adds ~a `routes.py` module to manage the names of the `urlpatterns`, a context processor for the module, and~ a simple template for the Caltrans Districts page and for the landing page of a Caltrans District.
=> Feat: URL setup for `districts` app

pems/districts/templates/districts/district.html, pems/districts/templates/districts/index.html, pems/districts/urls.py, pems/districts/views.py, tests/pytest/pems/districts/test_views.py
Closes #68
This PR adds UI placeholders for the `districts` application.
Click around to test out the navigation sidebar to go from all districts to a particular district.
=> Feat: UI templates for the `districts` application

pems/districts/templates/districts/index.html, pems/districts/templates/districts/navigation.html
This PR implements highlighting the active District in the navigation sidebar and moves the sidebar to a separate template for modularity.
=> Feat: highlight active District in sidebar

.devcontainer/Dockerfile, .env.sample, compose.yml
Closes #107 
<details>
<summary>WIP (for context)</summary>
It's sort of a hassle that the AWS CLI installer is different per platform and that `apt-get` is not updated often, it installs version 2.9 and the current one is 2.27. I would have also thought that the `Linux x86` installer would have worked in the dev container even if the host is a Mac since the base image is multi-platform, but after installation, the `aws` command fails. 
This failure prompted this approach of determining the host architecture ~and passing it as an argument in the build process. The `dev` service successfully builds if we build it using the `bin/build.sh` script. Still trying to see how to work this in to VS Code's "Rebuild and Reopen in Container" command. We need to pass a dynamically generated …
=> Chore: add AWS dev tools

docs/development/README.md
Part of #108
This PR adds documentation for how to set up the dev container to work with the Cloud infrastructure. Currently it will only be used by Compiler devs so we can add more details and polish the presentation at a later time when the docs site is more fleshed out.
=> Docs: Cloud infra development

.github/workflows/deploy.yml, copilot/.workspace, copilot/environments/dev/manifest.yml, copilot/streamlit/manifest.yml, copilot/web/manifest.yml, streamlit_app/Dockerfile, streamlit_app/requirements.txt
Closes #112, closes #113
This PR sets up the Cloud infrastructure using [AWS Copilot](https://aws.github.io/copilot-cli/) for the following two [services](https://aws.github.io/copilot-cli/docs/concepts/services/) under the `pems` Copilot [application](https://aws.github.io/copilot-cli/docs/concepts/applications/):
- `web`: The web UI/Internet-facing service (Load Balanced Web Service) - successfully deployed manually ✅ 
- `streamlit`: The data visualization via Streamlit service (Back-end Service) - successfully deployed manually ✅ 
It also modifies the `deploy` workflow to deploy the services to an AWS `dev` environment and does not publish the service images to the GitHub Container Registry anymore since the images are now stored on the Amazon Elastic Container Registry.
Separately, an …
=> Feat: set up Cloud infrastructure

.github/workflows/deploy.yml
We noticed in https://github.com/compilerla/pems/pull/111#issuecomment-2931033629 that there was already a folder called `copilot` in the location where curl was originally trying to install the `copilot` binary.
This fix installs `copilot` in a different directory to avoid the conflict.
=> Fix: install copilot in deploy workflow

.github/workflows/deploy.yml
Closes #134
Run the copilot CLI from the `infra` folder where it can discover the manifests for the copilot app.
=> Fix: run the copilot CLI from the correct directory

.devcontainer/devcontainer.json, infra/cloudformation/gh_actions.yml, infra/cloudformation/parameter_store.yml, pyproject.toml
This PR, related to #144, commits CloudFormation templates for resources that are not managed by AWS Copilot:
- GitHub Actions Identity Provider and Role
- Parameter Store Parameters
In addition, it adds a [template linter](https://github.com/aws-cloudformation/cfn-lint) and its [VS Code extension](https://marketplace.visualstudio.com/items?itemName=kddejong.vscode-cfn-lint) to the dev container.
=> Feat: CloudFormation templates for resources not managed by Copilot

.github/workflows/deploy.yml
This PR fixes a typo (missing a backslash at the end of a line) in the `aws cloudformation update-stack` command in the `Deploy` workflow that was responsible for this failed [workflow run](https://github.com/compilerla/pems/actions/runs/16267816236/job/45927629178).
=> Fix: typo in `update-stack` command

.github/workflows/deploy.yml
Although some references suggested that `github.environment` could be used to obtain the environment's name, testing the workflow showed that `github.environment` is actually not available in the context.
Instead, we set `ENVIRONMENT_NAME` for each environment and use`vars.ENVIRONMENT_NAME` to get the name of the deployment environment for the workflow. This will fix the failed [workflow run](https://github.com/compilerla/pems/actions/runs/16298115294/job/46025312212).
=> Fix: deployment environment name

.github/CODEOWNERS
So @compilerla/pems can approve changes to PeMS documentation.
=> Chore: add CODEOWNERS for docs

infra/copilot/streamlit/addons/s3-marts-access-policy.yml
Closes #185
Add a policy (as a Copilot addon) for accessing the S3 marts bucket from the ECS `streamlit` task via its Task role.
Using a `ManagedPolicy` is the most straightforward way to add permissions to the Copilot-created  ECS `streamlit` [`TaskRole`](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html).
To see how the CloudFormation templates created by Copilot will look like when adding the `s3-marts-access-policy` addon, run
```
copilot svc package --name streamlit --env dev --output-dir .
```
from the `infra` folder. The command will create 3 files (parameters, main stack template, and addon stack template) in `infra`. The addon stack template is essentially the template in this PR (with a few formatting changes) and the main stack template and …
=> Fix: policy to access the S3 marts bucket

.devcontainer/devcontainer.json, .env.sample, compose.yml, pems_data/pyproject.toml, pems_data/src/pems_data/__init__.py, pems_data/src/pems_data/cache.py, pems_data/src/pems_data/cli.py, pems_data/src/pems_data/serialization.py, pems_data/src/pems_data/services/stations.py, pems_data/src/pems_data/sources/cache.py, pems_streamlit/src/pems_streamlit/apps/stations/app_stations.py, tests/pytest/pems_data/conftest.py, tests/pytest/pems_data/services/test_stations.py, tests/pytest/pems_data/sources/test_cache.py, tests/pytest/pems_data/sources/test_s3.py, tests/pytest/pems_data/test_cache.py, tests/pytest/pems_data/test_init.py, tests/pytest/pems_data/test_serialization.py
Closes #198 
_See #196 for docs that describe `pems_data` architecture and usage_
Introduces a caching layer for `pems_data` that is mostly transparent for users/callers of `pems_data` functionality.
The main caching interface is defined in the `pems_data.cache.Cache` class, which is a wrapper around a `redis` connection.
`redis` is added as a local Compose service, and the `pems-cache` CLI is added to help debug and inspect the cache.
* Establishes and manages a connection to `redis`
* Defines `get` and `set` wrappers
* Helpers to `get`/`set` DataFrames from the cache
An `IDataSource` implementation (see #187) that wraps _another_ `IDataSource` and calls out to the cache first before performing any needed `.read()` operations on the underlying data source. Data returned from `.read()` is …
=> Feat: `pems_data` caching
